spring:
  redis:
    host: 120.77.234.251
    port: 6379
    password: $Fortune2017
    timeout: 3000
    database: 3
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms